Enable on-the-fly haplotag for simulated reads

diff --git a/scripts/synthBAM b/scripts/synthBAM
--- a/scripts/synthBAM
+++ b/scripts/synthBAM
@@ -6,7 +6,9 @@ REFERENCE=human_g1k_v37.fasta
 SHAREDREF=
 SAMPLE=
 STATSPATH=
-GNOMADCOVGPATH=
+PHASE_REGION=
+PHASE_VCF=
+PHASE_SAMPLE=
 
 COVERAGE=20
 FRAGMEAN=400
@@ -49,10 +51,13 @@ Options:
   -n string     Sample name, default: undefined
   -j FILE       NPSV stats file for GC normalized coverage, default: undefined
   -g FILE       Path to gnomAD coverage file, default: undefined
+  -v FILE       Phased VCF (if specified, phasing region and phasing sample must be specified), default: undefined
+  -r string     Region for phasing, default: undefined
+  -N string     Sample in phased VCF, default: undefined
 EOF
 }
 
-while getopts "hR:S:c:m:s:t:l:p:z:i:p:n:j:g:" Option
+while getopts "hR:S:c:m:s:t:l:p:z:i:p:n:j:g:r:v:N:" Option
 do
     case $Option in
         R)
@@ -91,8 +96,14 @@ do
         j)
             STATSPATH=$OPTARG
             ;;
-        g)
-            GNOMADCOVGPATH=$OPTARG
+        r)
+            PHASE_REGION=$OPTARG
+            ;;
+        v)
+            PHASE_VCF=$OPTARG
+            ;;
+        N)
+            PHASE_SAMPLE=$OPTARG
             ;;
         h)
             usage
@@ -131,9 +142,15 @@ if [[ -z $SHAREDREF ]]; then
     SHAREDREF="$REFERENCE"
 fi
 
+if [[ -n "$PHASEDVCF" && (-z "$PHASE_REGION" || -z "$PHASE_SAMPLE") ]]; then
+    >&2 echo "Error: Phase region and sample must be specified with phasing VCF"
+    >&2 usage
+    exit 1
+fi
+
 for (( s=1; s<=SAMPLES; s++ ))
 do
-    if [[ -z $SAMPLE ]]; then
+    if [[ -z "$SAMPLE" ]]; then
         SM="synth${s}"
     else
         SM="$SAMPLE"
@@ -142,20 +159,17 @@ do
     READS_PREFIX=$TMPDIR/reads.synth${s}
     art_illumina -q -i "$FASTA" -o "$READS_PREFIX" -sam -ss "$PROFILE" -l "$LENGTH" -f "$COVERAGE" -p -m "$FRAGMEAN" -s "$FRAGSD" -sp -rs $(od -An -tu4 -N4 /dev/urandom) 1>&2
     
+    # If SNV haplotyping used, there might be contigs with "_hap[0-1]" append, remove the suffix from sequence entries and read contigs 
+    awk '/^@/ { $2=gensub(/_hap[0-1]$/, "", 1, $2); print; } !/^@/ { $3=gensub(/_hap[0-1]$/, "", 1, $3); print; }' "${READS_PREFIX}.sam" | \
+        uniq > "${READ_PREFIX}.sam.tmp" && mv "${READ_PREFIX}.sam.tmp" "${READS_PREFIX}.sam"
+    
     >&2 echo "Generating aligned BAM"
     # Generate synthetic aligned BAM using minimal, but representative, pipeline
     # This pipeline should be modified to make the simulated pipeline similar to the
     # the pipeline used with the actual data
     ALIGNEDBAM=$TMPDIR/aligned${s}.bam
     
-    if [[ -n $GNOMADCOVGPATH ]]; then
-        # Downsample reads based on GnomAD coverage profile
-        npsv2u gnomad_covg --covg-path "$GNOMADCOVGPATH" -i "${READS_PREFIX}.sam" | \
-        bwa mem -p -c 250 -M -v 1 -I "${FRAGMEAN},${FRAGSD}" \
-            -R "@RG\tID:synth${s}\tSM:${SM}\tLB:synth${s}\tPL:illumina\tPU:ART" \
-            "$SHAREDREF" \
-            /dev/stdin 
-    elif [[ -n $STATSFILE ]]; then
+    if [[ -n "$STATSFILE" ]]; then
         # Downsample reads based on GC fraction
         npsv2u gc_covg --fasta-path "$FASTA" --stats-path "$STATSFILE" -i "${READS_PREFIX}.sam" | \
         bwa mem -p -c 250 -M -v 1 -I "${FRAGMEAN},${FRAGSD}" \
@@ -164,16 +178,33 @@ do
             /dev/stdin
     else
         # bwa mem -Y -v 1 -I "${FRAGMEAN},${FRAGSD}" \
-        # bwa mem -c 250 -M -v 1 -I "${FRAGMEAN},${FRAGSD}" \
         bwa mem -c 250 -M -v 1 -I "${FRAGMEAN},${FRAGSD}" \
             -R "@RG\tID:synth${s}\tSM:${SM}\tLB:synth${s}\tPL:illumina\tPU:ART" \
             "$SHAREDREF" \
             "${READS_PREFIX}1.fq" "${READS_PREFIX}2.fq"
     fi | \
     samblaster -q -M --addMateTags | \
-    add_HP_tag | \
+    if [[ -n "$PHASE_VCF" ]]; then
+        cat
+    else
+        add_HP_tag
+    fi | \
     samtools view -S -u  - | \
     sambamba -q sort -t 1 -m 512MiB --tmpdir="$TMPDIR" -o "$ALIGNEDBAM" /dev/stdin
+    
+    if [[ -n "$PHASED_VCF" ]]; then
+        whatshap haplotag \
+            --tag-supplementary \
+            --ignore-read-groups \
+            --reference $REFERENCE \
+            --regions $PHASE_REGION \
+            --sample $PHASE_SAMPLE \
+            -o "${ALIGNEDBAM/%bam/phase.bam}" \
+            $PHASE_VCF \
+            $ALIGNEDBAM
+        mv "${ALIGNEDBAM/%bam/phase.bam}" $ALIGNEDBAM
+        samtools index $ALIGNEDBAM
+    fi
 
     # Cleanup files generated by ART
     rm -f "${READS_PREFIX}.sam" "${READS_PREFIX}1.fq" "${READS_PREFIX}2.fq" "${READS_PREFIX}1.aln" "${READS_PREFIX}2.aln"
